version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tiao_carreiro
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
